# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 19]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          ssh-keygen -t ed25519 -C 'shipittest@uscreen.me' -q -N "" -f ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host *
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END

      - name: Start testhost
        run: |
          docker run -d --rm \
          -e AUTHORIZED_KEYS="$(cat ~/.ssh/*.pub)" \
          -p 2222:22 \
          --name shipit-deploy-cd-testhost \
          $(docker build -q ./tests)

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Stop & remove testhost
        run: docker stop shipit-deploy-cd-testhost

  automerge:
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
